### PR TITLE
yesod 1.2 compatibility

### PR DESCRIPTION
**Pull request by gregwebs**

### CODE REVIEW

**Comment by gregwebs** [comment]
actually, the move from Yesod.Foo -> Yesod.Core.Foo is a big breakage. For example, it breaks yesod-markdown. Should we keep the old module names around until yesod version 2 ?

**Comment by snoyberg** [comment]
I don't think this change is sufficient to get yesod-fay building. You should check out:

https://github.com/fpco/yesod-fay/tree/yesod1.2

In fact, it might make sense to just close this repo and have it point at the fpco copy, which is what we use internally.

**Comment by snoyberg** [comment]
I'm hoping the Yesod.Foo -> Yesod.Core.Foo isn't a big change: everyone should just use Yesod.Core for _all_ imports. That works for both yesod-core 1.1 and 1.2. I'd rather not have the old module names, as it will make the documentation more confusing to approach.

**Comment by gregwebs** [comment]
ok, if it works for 1.1 it should be alright.
Closing this repos is good, but you might consider wiping out the files and pointing the README to the new location.
Does it make sense to put yesod-fay under yesodweb ?

**Comment by snoyberg** [comment]
OK, I've wiped all files but the README, pointing to fpco.

For now, I think it makes more sense to keep the main repo on fpco. I'm not yet ready to promote yesod-fay to a fully recommended project, until there's been a bit more stability in it. And in the interim, we're actively making changes to it for our purposes, so synchronizing between a yesodweb and fpco copy would just be an annoyance for users I think.

**Comment by qrilka** [comment]
@snoyberg And what are your plans for it? Any stable version this Spring?

**Comment by snoyberg** [comment]
I'm planning on releasing yesod-fay together with the rest of the yesod 1.2 release. What I meant is that Fay itself is still not a stable project, so I can't really recommend yesod-fay as stable either. (That's not to say I don't think it's useful, we built our entire site using it.)

**Comment by qrilka** [comment]
It would be great to read some blog posts on your experience with it if you will have some time later.

**Comment by snoyberg** [comment]
The top item in my blog post list is on our usage of Fay. I really will get to it soon. Hopefully.

**Pull request closed without merging**
