### PR TITLE
Updates for Fay 0.13

### PR DESCRIPTION
**Pull request by qrilka**
Fixes #6

### CODE REVIEW

**Comment by snoyberg** [comment]
Thank you for the pull request. I'm purposely delaying the merge of it since Fay 0.13 is in a bit of upheaval right now, and I have my own branch which provides this support as well to some degree. Once the dust settles I'll look more carefully at this patch.

**Comment by alexanderkjeldaas** [comment]
Any update on this, or support for fay 0.14?

**Comment by snoyberg** [comment]
I just pushed yesod-fay 0.3.0 to Hackage, with support for fay 0.14. Can you test that out?

**Comment by qrilka** [comment]
Tested against Fay 0.14.1

**Pull request closed without merging**
